In [1]:
import sympy as sp
from sympy.physics import units as u

In [2]:
hbar = u.Quantity(r'hbar',latex_repr='\hbar',math_ml_representation='\hbar')
hbar.set_global_relative_scale_factor(10,u.joule*u.second)

In [3]:
hbar

hbar

In [4]:
m = u.Quantity('m')
m.set_global_relative_scale_factor(sp.symbols('m'),u.kilogram)


type(u.util.convert_to(m,u.kilogram).args[1])#.free_symbols

In [5]:
g = sp.symbols(r"\epsilon")


In [6]:
g.name==r"\epsilon"

True

In [7]:
import numpy as np

In [8]:
c = np.complex128

In [9]:
A = [[c(1),c(2),c(3)],[0,1,2],[0,3,3.0*g]]

In [10]:
A

[[(1+0j), (2+0j), (3+0j)], [0, 1, 2], [0, 3, 3.0*\epsilon]]

In [11]:
a=sp.Array(A)

In [12]:
for at in a.atoms():
    print(type(at))

<class 'sympy.core.numbers.Zero'>
<class 'sympy.core.numbers.One'>
<class 'sympy.core.numbers.Integer'>
<class 'sympy.core.numbers.Integer'>
<class 'sympy.core.symbol.Symbol'>
<class 'sympy.core.numbers.Float'>
<class 'sympy.core.numbers.Float'>
<class 'sympy.core.numbers.Float'>


In [13]:
def func(x):
    print(x)
    try:
        return c(x)
    except Exception as err:
        return x

aa=a.applyfunc(func)

1.00000000000000
2.00000000000000
3.00000000000000
0
1
2
0
3
3.0*\epsilon


In [14]:
kprint([(type(at),at) for at in aa.atoms()])

NameError: name 'kprint' is not defined

In [ ]:
aa.to_numpy()

In [ ]:
na=np.array(a)

In [ ]:
npf = np.vectorize(func)

In [ ]:
old_shape = na.shape
np.array([func(x) for x in na.flatten()]).reshape(old_shape)

In [ ]:
type(c(na[0,0]))

In [ ]:
aa

In [ ]:
sp.lambdify(g,aa)(d)[-1,-1]

In [ ]:
e = sp.symbols('e')

In [ ]:
class Dummy():
    def __init__(self) -> None:
        self.x=1

In [ ]:
d = Dummy()

In [ ]:
from unittest.mock import mock_open,patch
import pickle
M = mock_open()
temp = [1,2,3]
with patch('__main__.open',M):
    with open('filename.temp','wb') as f:
        pickle.dump(temp,f)
    
    with open('filename.temp',mode='rb') as ff:
        print(ff)
        print(pickle.load(ff))
        

In [ ]:
from sympy.physics.units.quantities import Quantity
from sympy.physics.units.systems.si import SI
import sympy.physics.units as u
_hbar = Quantity('hbar',latex_repr='\hbar',mathml_presentation_repr='hbar') # plancks constant
_hbar.set_global_relative_scale_factor(1.054571817e-34,u.joule*u.second)
_m_e = Quantity(name='m\_e',mathml_representation_repr='m_e',latex_repr='m_e',pretty_ascii_repr='m_e',pretty_unicode_repr='m_e') # electron mass
_m_e.set_global_relative_scale_factor(9.1093837015e-31,u.kilogram)

In [ ]:
A = sp.Array([[_hbar**2/(2*_m_e)*(kkx**2+kky**2+kkz**2),0],[0,_hbar**2/(2*_m_e)*(kkx**2+kky**2+kkz**2)]])

In [ ]:
kx,ky,kz = sp.symbols(r'kx,ky,kz')
kkx = u.Quantity('k\_x')
kkx.set_global_relative_scale_factor(kx,1/u.meter)
kky = u.Quantity('k\_y')
kky.set_global_relative_scale_factor(ky,1/u.meter)
kkz = u.Quantity('k\_z')
kkz.set_global_relative_scale_factor(kz,1/u.meter)

In [ ]:
sp.sympify(u.convert_to(A[0,0],u.joule)).atoms(sp.Symbol)

In [ ]:
A

In [ ]:
for s in A.atoms(u.Quantity):
    print(s,s.scale_factor,s.dimension)

In [ ]:
for s in A.atoms(sp.Symbol):
    

In [ ]:
kx,ky,kz = sp.symbols(r'kx,ky,kz')
A = sp.Array([[kx,ky,kz]])

In [ ]:
A

[[kx, ky, kz]]

In [ ]:
AL=sp.lambdify((kx,ky,kz),A)

In [ ]:
AL(*np.array([0,1,2]))

array([[0, 1, 2]])

In [ ]:
K = np.stack([np.array([0,1,2]),2*np.array([0,1,2])])
K

array([[0, 1, 2],
       [0, 2, 4]])

In [ ]:
AL(*K.T).transpose((-1,0,1))

array([[[0, 1, 2]],

       [[0, 2, 4]]])

In [ ]:
import sympy as sp
import numpy as np

In [ ]:
A = sp.Array([[1,2],[3,4]])

In [ ]:
A

[[1, 2], [3, 4]]

In [ ]:
A.copy()
kx = sp.symbols('k_x')

In [ ]:
A

[[1, 2], [3, 4]]

In [ ]:
A = sp.Array([[1*kx,2],[3,4*kx]])

In [ ]:
A.conjugate().subs({kx:sp.conjugate(kx)})

[[k_x, 2], [3, 4*k_x]]

In [ ]:
B = sp.Array([[[[1,0],[0,0]],[[2,0],[3,0]]],[[[10,0],[0,0]],[[20,0],[30,0]]]])
B.shape
B.reshape(2,8)

[[1, 0, 0, 0, 2, 0, 3, 0], [10, 0, 0, 0, 20, 0, 30, 0]]

In [ ]:
sp.Array(sp.matrices.expressions.blockmatrix.BlockDiagMatrix(sp.Matrix(A),sp.Matrix(A)))

Matrix([
[Matrix([
[k_x,     2],
[  3, 4*k_x]]),                                     0],
[                                    0, Matrix([
[k_x,     2],
[  3, 4*k_x]])]])

In [ ]:
B

[[[[1, 0], [0, 0]], [[2, 0], [3, 0]]], [[[10, 0], [0, 0]], [[20, 0], [30, 0]]]]

In [ ]:
b=np.array(B)

In [ ]:
b.ravel()

array([1, 0, 0, 0, 2, 0, 3, 0, 10, 0, 0, 0, 20, 0, 30, 0], dtype=object)

In [ ]:
b.reshape(4,4)

array([[1, 0, 0, 0],
       [2, 0, 3, 0],
       [10, 0, 0, 0],
       [20, 0, 30, 0]], dtype=object)

In [ ]:
BB= sp.tensor.array.permutedims(B,(0,2,1,3))




In [ ]:
U = sympy.array([[0,1],[-1,0]])
UU = sympy.tensordot( )

NameError: name 'sympy' is not defined

In [ ]:
BB = BB.reshape(4,4)
BB

[[1, 0, 2, 0], [0, 0, 3, 0], [10, 0, 20, 0], [0, 0, 30, 0]]

In [ ]:
B

[[[[1, 0], [0, 0]], [[2, 0], [3, 0]]], [[[10, 0], [0, 0]], [[20, 0], [30, 0]]]]

In [ ]:
Bex = sp.Array(sp.Matrix(sp.matrices.expressions.blockmatrix.BlockDiagMatrix(sp.Matrix(BB),-sp.Matrix(BB))))

In [ ]:
Bex

[[1, 0, 2, 0, 0, 0, 0, 0], [0, 0, 3, 0, 0, 0, 0, 0], [10, 0, 20, 0, 0, 0, 0, 0], [0, 0, 30, 0, 0, 0, 0, 0], [0, 0, 0, 0, -1, 0, -2, 0], [0, 0, 0, 0, 0, 0, -3, 0], [0, 0, 0, 0, -10, 0, -20, 0], [0, 0, 0, 0, 0, 0, -30, 0]]

In [ ]:
final= sp.tensor.array.permutedims(Bex.reshape(4,2,4,2),(0,2,1,3))

In [ ]:
final

[[[[1, 0], [0, 0]], [[2, 0], [3, 0]], [[0, 0], [0, 0]], [[0, 0], [0, 0]]], [[[10, 0], [0, 0]], [[20, 0], [30, 0]], [[0, 0], [0, 0]], [[0, 0], [0, 0]]], [[[0, 0], [0, 0]], [[0, 0], [0, 0]], [[-1, 0], [0, 0]], [[-2, 0], [-3, 0]]], [[[0, 0], [0, 0]], [[0, 0], [0, 0]], [[-10, 0], [0, 0]], [[-20, 0], [-30, 0]]]]

In [ ]:
NN = np.array(final)

In [ ]:
np.transpose(NN,(1,0,...))

TypeError: 'ellipsis' object cannot be interpreted as an integer

[[0, 0], [0, 0]]

In [ ]:
NN=np.array(final)
NN[slice(0,2),slice(2,4)] = np.arange(16).reshape((2,2,2,2))*10+1
sp.Array(NN)

[[[[1, 0], [0, 0]], [[2, 0], [3, 0]], [[1, 11], [21, 31]], [[41, 51], [61, 71]]], [[[10, 0], [0, 0]], [[20, 0], [30, 0]], [[81, 91], [101, 111]], [[121, 131], [141, 151]]], [[[0, 0], [0, 0]], [[0, 0], [0, 0]], [[-1, 0], [0, 0]], [[-2, 0], [-3, 0]]], [[[0, 0], [0, 0]], [[0, 0], [0, 0]], [[-10, 0], [0, 0]], [[-20, 0], [-30, 0]]]]

In [ ]:
class foo():
    __t__ = 't'
    def __init__(self,x):
        self.x=x
    

In [ ]:
F=foo(1)

In [ ]:
F.x
F.__t__

't'

In [ ]:
from zmq import EVENT_CLOSE_FAILED


def recursion_term(A,N):
    # floating point error becomes too large at N>15 
    
    if N==2:
        if A%2:
            return 4/(np.pi*A)-8/(np.pi*A)**3
        else:
            return 0 
    if N==1:
        if A%2:
            return 0
        else:
            return -4/(A*np.pi)
    return -4/(A*np.pi)*(1+N*(N-1)/(A*np.pi)*recursion_term(A,N-2))


In [ ]:
recursion_term(2,25)

-0.00820576285190685

In [ ]:
L=1
def x_mat(n,m,order):
    if (not order%2) or ():
        return 0 % odd powers of x vanish  
    expr = (2/L)**oder *order * 

SyntaxError: invalid syntax (1418258481.py, line 1)

In [ ]:
import numpy as np

In [ ]:
from nqcpsim.band_model import ANGULAR_MOMENTUM

ModuleNotFoundError: No module named 'nqcpsim'

In [ ]:
(.4)/(2*(1.2))

0.16666666666666669

In [ ]:
aa=sp.Matrix(A)

In [ ]:
aa

Matrix([
[1.0, 2.0,          3.0],
[  0,   1,            2],
[  0,   3, 3.0*\epsilon]])

In [ ]:
aa.T

Matrix([
[1.0, 0,            0],
[2.0, 1,            3],
[3.0, 2, 3.0*\epsilon]])

In [ ]:
x,y = sp.symbols('x,y')

In [ ]:
A =sp.Matrix([[x,y,1],[y,x,2],[x,y,3]])

In [ ]:

B=sp.Matrix([[10,20,30]]).T

In [ ]:
list(A@B)

[10*x + 20*y + 30, 20*x + 10*y + 60, 10*x + 20*y + 90]

In [ ]:
A.subs({x:y,y:x})

[[x, x, 1], [x, x, 2]]

In [69]:
x,z = sp.symbols('x,z',commutative =False)
y,a = sp.symbols('y,a')

In [57]:
expr = a*x + x**2 +2*x*a*x+ y*y*x*x*y+ x*z*x*z*a
expr

a*x + a*x*z*x*z + 2*a*x**2 + y**3*x**2 + x**2

In [44]:
isinstance(expr,sp.Add)

True

In [49]:
expr.args


(x**2, a*x, y**3*x**2, 2*a*x**2)

In [55]:
expr.args[0].coeff(x**4)

0

In [46]:
from sympy.polys.polytools import degree

In [48]:
degree(expr.args[0],x)


GeneratorsError: non-commutative generators: (x,)

In [62]:
D=sp.Dummy(commutative=False)

In [64]:
D.is_commutative

False

In [73]:
EX = x*(z+2)+(z+2)*x

In [74]:
isinstance(EX,sp.Add)

True

In [76]:
EX.args

(x*(2 + z), (2 + z)*x)

In [79]:
EX.args[0].subs({x:y,z:a})

y*(a + 2)

In [81]:
EX.simplify()

x*(2 + z) + (2 + z)*x

In [93]:
from sympy.simplify import separatevars
L=separatevars(EX,symbols=(x,z),dict=True)

In [94]:
L is None

True

In [97]:
EX.expand()

4*x + x*z + z*x